/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GatedRouteImport } from './routes/_gated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as GatedIndexRouteImport } from './routes/_gated.index'
import { Route as GatedAgendaRouteImport } from './routes/_gated.agenda'
import { Route as GatedAnaliseRouteImport } from './routes/_gated.analise'
import { Route as GatedComoUsarRouteImport } from './routes/_gated.como-usar'
import { Route as GatedConfiguracoesRouteImport } from './routes/_gated.configuracoes'
import { Route as GatedContasRouteImport } from './routes/_gated.contas'
import { Route as GatedImportarRouteImport } from './routes/_gated.importar'
import { Route as GatedMetasRouteImport } from './routes/_gated.metas'
import { Route as GatedPaineisRouteImport } from './routes/_gated.paineis'
import { Route as GatedRelatoriosRouteImport } from './routes/_gated.relatorios'
import { Route as GatedPaginaIdRouteImport } from './routes/_gated.pagina.$id'

const GatedRoute = GatedRouteImport.update({
  id: '/_gated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GatedIndexRoute = GatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GatedRoute,
} as any)
const GatedAgendaRoute = GatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => GatedRoute,
} as any)
const GatedAnaliseRoute = GatedAnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => GatedRoute,
} as any)
const GatedComoUsarRoute = GatedComoUsarRouteImport.update({
  id: '/como-usar',
  path: '/como-usar',
  getParentRoute: () => GatedRoute,
} as any)
const GatedConfiguracoesRoute = GatedConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => GatedRoute,
} as any)
const GatedContasRoute = GatedContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => GatedRoute,
} as any)
const GatedImportarRoute = GatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => GatedRoute,
} as any)
const GatedMetasRoute = GatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => GatedRoute,
} as any)
const GatedPaineisRoute = GatedPaineisRouteImport.update({
  id: '/paineis',
  path: '/paineis',
  getParentRoute: () => GatedRoute,
} as any)
const GatedRelatoriosRoute = GatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => GatedRoute,
} as any)
const GatedPaginaIdRoute = GatedPaginaIdRouteImport.update({
  id: '/pagina/$id',
  path: '/pagina/$id',
  getParentRoute: () => GatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof GatedIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agenda': typeof GatedAgendaRoute
  '/analise': typeof GatedAnaliseRoute
  '/como-usar': typeof GatedComoUsarRoute
  '/configuracoes': typeof GatedConfiguracoesRoute
  '/contas': typeof GatedContasRoute
  '/importar': typeof GatedImportarRoute
  '/metas': typeof GatedMetasRoute
  '/paineis': typeof GatedPaineisRoute
  '/relatorios': typeof GatedRelatoriosRoute
  '/pagina/$id': typeof GatedPaginaIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agenda': typeof GatedAgendaRoute
  '/analise': typeof GatedAnaliseRoute
  '/como-usar': typeof GatedComoUsarRoute
  '/configuracoes': typeof GatedConfiguracoesRoute
  '/contas': typeof GatedContasRoute
  '/importar': typeof GatedImportarRoute
  '/metas': typeof GatedMetasRoute
  '/paineis': typeof GatedPaineisRoute
  '/relatorios': typeof GatedRelatoriosRoute
  '/': typeof GatedIndexRoute
  '/pagina/$id': typeof GatedPaginaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_gated': typeof GatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_gated/agenda': typeof GatedAgendaRoute
  '/_gated/analise': typeof GatedAnaliseRoute
  '/_gated/como-usar': typeof GatedComoUsarRoute
  '/_gated/configuracoes': typeof GatedConfiguracoesRoute
  '/_gated/contas': typeof GatedContasRoute
  '/_gated/importar': typeof GatedImportarRoute
  '/_gated/metas': typeof GatedMetasRoute
  '/_gated/paineis': typeof GatedPaineisRoute
  '/_gated/relatorios': typeof GatedRelatoriosRoute
  '/_gated/': typeof GatedIndexRoute
  '/_gated/pagina/$id': typeof GatedPaginaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/agenda'
    | '/analise'
    | '/como-usar'
    | '/configuracoes'
    | '/contas'
    | '/importar'
    | '/metas'
    | '/paineis'
    | '/relatorios'
    | '/pagina/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/agenda'
    | '/analise'
    | '/como-usar'
    | '/configuracoes'
    | '/contas'
    | '/importar'
    | '/metas'
    | '/paineis'
    | '/relatorios'
    | '/'
    | '/pagina/$id'
  id:
    | '__root__'
    | '/_gated'
    | '/login'
    | '/reset-password'
    | '/_gated/agenda'
    | '/_gated/analise'
    | '/_gated/como-usar'
    | '/_gated/configuracoes'
    | '/_gated/contas'
    | '/_gated/importar'
    | '/_gated/metas'
    | '/_gated/paineis'
    | '/_gated/relatorios'
    | '/_gated/'
    | '/_gated/pagina/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GatedRoute: typeof GatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_gated': {
      id: '/_gated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gated/': {
      id: '/_gated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GatedIndexRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/agenda': {
      id: '/_gated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof GatedAgendaRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/analise': {
      id: '/_gated/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof GatedAnaliseRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/como-usar': {
      id: '/_gated/como-usar'
      path: '/como-usar'
      fullPath: '/como-usar'
      preLoaderRoute: typeof GatedComoUsarRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/configuracoes': {
      id: '/_gated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof GatedConfiguracoesRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/contas': {
      id: '/_gated/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof GatedContasRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/importar': {
      id: '/_gated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof GatedImportarRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/metas': {
      id: '/_gated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof GatedMetasRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/paineis': {
      id: '/_gated/paineis'
      path: '/paineis'
      fullPath: '/paineis'
      preLoaderRoute: typeof GatedPaineisRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/relatorios': {
      id: '/_gated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof GatedRelatoriosRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/pagina/$id': {
      id: '/_gated/pagina/$id'
      path: '/pagina/$id'
      fullPath: '/pagina/$id'
      preLoaderRoute: typeof GatedPaginaIdRouteImport
      parentRoute: typeof GatedRoute
    }
  }
}

interface GatedRouteChildren {
  GatedAgendaRoute: typeof GatedAgendaRoute
  GatedAnaliseRoute: typeof GatedAnaliseRoute
  GatedComoUsarRoute: typeof GatedComoUsarRoute
  GatedConfiguracoesRoute: typeof GatedConfiguracoesRoute
  GatedContasRoute: typeof GatedContasRoute
  GatedImportarRoute: typeof GatedImportarRoute
  GatedMetasRoute: typeof GatedMetasRoute
  GatedPaineisRoute: typeof GatedPaineisRoute
  GatedRelatoriosRoute: typeof GatedRelatoriosRoute
  GatedIndexRoute: typeof GatedIndexRoute
  GatedPaginaIdRoute: typeof GatedPaginaIdRoute
}

const GatedRouteChildren: GatedRouteChildren = {
  GatedAgendaRoute: GatedAgendaRoute,
  GatedAnaliseRoute: GatedAnaliseRoute,
  GatedComoUsarRoute: GatedComoUsarRoute,
  GatedConfiguracoesRoute: GatedConfiguracoesRoute,
  GatedContasRoute: GatedContasRoute,
  GatedImportarRoute: GatedImportarRoute,
  GatedMetasRoute: GatedMetasRoute,
  GatedPaineisRoute: GatedPaineisRoute,
  GatedRelatoriosRoute: GatedRelatoriosRoute,
  GatedIndexRoute: GatedIndexRoute,
  GatedPaginaIdRoute: GatedPaginaIdRoute,
}

const GatedRouteWithChildren = GatedRoute._addFileChildren(GatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  GatedRoute: GatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
